name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy-to-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Unset CI Variable
        run: unset CI

      - name: Install Python and AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-dev python3-pip
          pip3 install awscli

      - name: Build and Deploy to Test Environment
        run: |
          npm install
          npm run build:test

      - name: Deploy to S3 Test Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: sushis.site
          AWS_ACCESS_KEY_ID: AKIA2D6TGRW3E4AOQFM3
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: eu-central-1
          SOURCE_DIR: 'build'

      - name: Invalidate Cloudfront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id EHF3TMZVG2Z2H --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: AKIA2D6TGRW3E4AOQFM3
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: eu-central-1